### ISSUE TITLE
Submission rules

### ISSUE THREAD

**Issue by PaulFreund** [PocketSprite/CodingChallenge#2]
Just a clarification question:
* When is the last date admissions are accepted
* I have different ideas, if I submitted already and change my mind can I change my submission or even submit multiple projects?
* Are external parts accepted? Like a companion PC application or other additional hardware? And if yes will that code/application be included in the ruling?

**Comment by Spritetm** [comment]
Let me get back on the first point; we'll possibly make Aug31th the deadline, then announce a winner after we've had the chance to deliberate. Furthermore, you can submit multiple projects; note however that we may be disinclined to have one person win multiple prices unless the separate projects are truly outstanding. For external components: they are accepted but keep in mind that we still need to be able to judge the project, and if the external hardware is not something we already have or can get or build easily/cheaply, we may not be able to judge your project as well as a standalone project.

**Comment by PaulFreund** [comment]
Thanks for the clarification. I would even go so far to limit one winning entry per person.
