### ISSUE TITLE
Can't create PR against empty repo?

### ISSUE THREAD

**Issue by rorosaurus** [PocketSprite/CodingChallenge#4]
When I click "new pull request" on this repo, I'm greeted with this.  I think it wants the repo to have some content already before you can compare/create PR's from the web.

![image](https://user-images.githubusercontent.com/908662/41885717-0e223f0c-78ae-11e8-89fb-9eb3ccb233e3.png)

**Comment by awhit003** [comment]
Same.

**Comment by rorosaurus** [comment]
Fixed by 0b02be5cbd0f1cb3e697353394c3ecd6629efdea
